import { join } from "node:path";
import { writeFile } from "node:fs/promises";
import { auditDir, ensureDir } from "../storage/fs";
import { loadConversation } from "../storage/conversations";
import { getAuditReport, findAuditById } from "../storage/audits";
import type { Audit, AuditReport, ChatMessage } from "../report/schema";

export type SessionExport = {
  audit_id: string;
  company_slug: string;
  filename: string;
  md_path: string;
  html_path: string;
  message_count: number;
  done_count: number;
};

export async function exportSession(auditId: string): Promise<SessionExport> {
  const audit = await findAuditById(auditId);
  if (!audit) throw new Error(`Audit not found: ${auditId}`);
  const report = await getAuditReport(audit.company_slug, audit.id);
  if (!report) throw new Error("Report missing");
  const conversation = await loadConversation(audit.company_slug, audit.id);

  const ts = new Date().toISOString().replace(/[:.]/g, "-");
  const slug = `${ts}.md`;
  const dir = join(auditDir(audit.company_slug, audit.id), "sessions");
  await ensureDir(dir);

  const md = renderMarkdown(audit, report, conversation.messages);
  const html = renderHtml(audit, report, conversation.messages, md);

  const mdPath = join(dir, slug);
  const htmlPath = mdPath.replace(/\.md$/, ".html");
  await writeFile(mdPath, md, "utf8");
  await writeFile(htmlPath, html, "utf8");

  return {
    audit_id: audit.id,
    company_slug: audit.company_slug,
    filename: slug.replace(/\.md$/, ""),
    md_path: mdPath,
    html_path: htmlPath,
    message_count: conversation.messages.length,
    done_count:
      (report.todo_list ?? []).filter((t) => t.status === "done").length +
      (report.implementation_plan ?? []).filter((p) => p.completed).length,
  };
}

function renderMarkdown(
  audit: Audit,
  report: AuditReport,
  messages: ChatMessage[],
): string {
  const lines: string[] = [];
  lines.push(`# Session report — ${report.site_name}`);
  lines.push("");
  lines.push(`- **URL:** ${report.source_value}`);
  lines.push(`- **Audit ID:** ${audit.id}`);
  lines.push(`- **Audit generated:** ${report.generated_at}`);
  lines.push(`- **Session exported:** ${new Date().toISOString()}`);
  lines.push("");
  lines.push("## Scores");
  lines.push("");
  lines.push(`- Overall: **${report.site_overall_score}** / 100`);
  lines.push(`- SEO:     **${report.site_seo_score}** / 100`);
  lines.push(`- GEO:     **${report.site_geo_score}** / 100`);
  lines.push(`- Pages audited: ${report.pages_audited}`);
  lines.push("");

  const doneTodos = (report.todo_list ?? []).filter(
    (t) => t.status === "done",
  );
  const openCritical = (report.todo_list ?? []).filter(
    (t) => (t.status ?? "open") !== "done" && t.severity === "critical",
  );
  const donePlan = (report.implementation_plan ?? []).filter((p) => p.completed);

  lines.push("## Actions taken this session");
  lines.push("");
  if (doneTodos.length === 0 && donePlan.length === 0) {
    lines.push("_No items marked done yet._");
  } else {
    if (doneTodos.length) {
      lines.push("**Closed TO-DO items:**");
      for (const t of doneTodos) lines.push(`- [x] ${t.id}: ${t.issue}`);
      lines.push("");
    }
    if (donePlan.length) {
      lines.push("**Completed implementation plan items:**");
      for (const p of donePlan)
        lines.push(`- [x] ${p.id}: ${p.action} (${p.priority})`);
      lines.push("");
    }
  }

  lines.push("## Open critical items");
  lines.push("");
  if (openCritical.length === 0) {
    lines.push("_None outstanding._");
  } else {
    for (const t of openCritical) {
      lines.push(`- [ ] **${t.id}** ${t.issue}`);
      lines.push(`  - Fix: ${t.fix}`);
    }
  }
  lines.push("");

  lines.push("## Q&A transcript");
  lines.push("");
  if (messages.length === 0) {
    lines.push("_No questions asked yet._");
  } else {
    for (const m of messages) {
      const who = m.role === "user" ? "You" : "Claude";
      lines.push(`### ${who} — ${m.created_at}`);
      lines.push("");
      lines.push(m.content);
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("Generated by SEO Audit Studio");
  return lines.join("\n");
}

function renderHtml(
  audit: Audit,
  report: AuditReport,
  messages: ChatMessage[],
  md: string,
): string {
  // Basic Markdown→HTML for the inline transcript (lists, headers, **bold**).
  const body = mdToHtml(md);
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Session report — ${escapeHtml(report.site_name)}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    :root {
      --bg: #0b0f19;
      --surface: #121826;
      --surface2: #1a2234;
      --border: #24304a;
      --text: #e6ecf5;
      --mute: #8b97ad;
      --accent: #6ea8ff;
      --good: #4ade80;
      --warn: #facc15;
      --bad: #f87171;
    }
    * { box-sizing: border-box; }
    body {
      font-family: "Plus Jakarta Sans", system-ui, -apple-system, sans-serif;
      background: var(--bg);
      color: var(--text);
      margin: 0;
      padding: 32px 24px 64px;
      line-height: 1.55;
    }
    main {
      max-width: 800px;
      margin: 0 auto;
    }
    h1 {
      font-size: 28px;
      margin: 0 0 8px;
    }
    h2 {
      font-size: 18px;
      color: var(--accent);
      margin: 32px 0 12px;
      padding-bottom: 6px;
      border-bottom: 1px solid var(--border);
    }
    h3 {
      font-size: 14px;
      color: var(--mute);
      margin: 20px 0 8px;
      font-weight: 600;
    }
    ul {
      padding-left: 20px;
    }
    code {
      background: var(--surface2);
      padding: 1px 5px;
      border-radius: 4px;
      font-size: 0.9em;
    }
    .meta {
      color: var(--mute);
      font-size: 13px;
    }
    .scores {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 12px;
      margin: 16px 0;
    }
    .score-card {
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 14px;
      text-align: center;
    }
    .score-card .v { font-size: 28px; font-weight: 700; }
    .good { color: var(--good); }
    .warn { color: var(--warn); }
    .bad { color: var(--bad); }
    blockquote {
      border-left: 3px solid var(--accent);
      margin: 12px 0;
      padding: 4px 12px;
      background: var(--surface);
      color: var(--text);
    }
    @media print {
      body { background: white; color: #111; }
      h2 { color: #444; border-color: #ccc; }
      .score-card { background: #f5f5f5; border-color: #ddd; }
    }
  </style>
</head>
<body>
<main>
  <h1>Session report — ${escapeHtml(report.site_name)}</h1>
  <p class="meta">${escapeHtml(report.source_value)} · audit ${audit.id}</p>
  <div class="scores">
    ${scoreCard("Overall", report.site_overall_score)}
    ${scoreCard("SEO", report.site_seo_score)}
    ${scoreCard("GEO", report.site_geo_score)}
  </div>
  ${body}
</main>
</body>
</html>`;
}

function scoreCard(label: string, value: number): string {
  const cls = value >= 70 ? "good" : value >= 40 ? "warn" : "bad";
  return `<div class="score-card"><div>${label}</div><div class="v ${cls}">${value}</div></div>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// Tiny Markdown→HTML for transcripts. Intentionally minimal:
// supports headers, **bold**, *italic*, `code`, and unordered lists.
function mdToHtml(md: string): string {
  const lines = md.split("\n");
  const out: string[] = [];
  let inList = false;
  for (const raw of lines) {
    const line = raw.trimEnd();
    if (line.startsWith("# ")) {
      if (inList) {
        out.push("</ul>");
        inList = false;
      }
      // Skip the H1, already rendered in template
      if (out.length > 0) out.push(`<h2>${inline(line.slice(2))}</h2>`);
      continue;
    }
    if (line.startsWith("## ")) {
      if (inList) {
        out.push("</ul>");
        inList = false;
      }
      out.push(`<h2>${inline(line.slice(3))}</h2>`);
      continue;
    }
    if (line.startsWith("### ")) {
      if (inList) {
        out.push("</ul>");
        inList = false;
      }
      out.push(`<h3>${inline(line.slice(4))}</h3>`);
      continue;
    }
    if (line.startsWith("- ")) {
      if (!inList) {
        out.push("<ul>");
        inList = true;
      }
      out.push(`<li>${inline(line.slice(2))}</li>`);
      continue;
    }
    if (line.startsWith("---")) {
      if (inList) {
        out.push("</ul>");
        inList = false;
      }
      out.push("<hr>");
      continue;
    }
    if (line === "") {
      if (inList) {
        out.push("</ul>");
        inList = false;
      }
      out.push("");
      continue;
    }
    if (inList) {
      out.push("</ul>");
      inList = false;
    }
    out.push(`<p>${inline(line)}</p>`);
  }
  if (inList) out.push("</ul>");
  return out.join("\n");
}

function inline(s: string): string {
  return escapeHtml(s)
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/(?<!\*)\*([^*]+)\*(?!\*)/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, "<code>$1</code>");
}
